{% set name = "sphinx-sitemap" %}
{% set version = "2.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jdillard/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dbf4b75777b60eb22fdc8222983d2c6a0229926902fc1d70077b9abbb4121b5c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - sphinx-last-updated-by-git

test:
  source_files:
    - tests
  imports:
    - sphinx_sitemap
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - gitpython
    - defusedxml

about:
  home: https://github.com/jdillard/sphinx-sitemap
  dev_url: https://github.com/jdillard/sphinx-sitemap
  doc_url: https://sphinx-sitemap.readthedocs.io
  summary: Sitemap generator for Sphinx
  description: |
    A Sphinx extension to generate multi-version and multi-language sitemaps.org compliant sitemaps 
    for the HTML version of your Sphinx documentation.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
