{% set version = "2.5.0" %}

package:
  name: sphinx-sitemap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx-sitemap/sphinx-sitemap-{{ version }}.tar.gz
  sha256: 95101f622d0d594161720cbe92a39d353efae9382f7f3563f06d150b1146fef6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - six
    - sphinx >=1.2

test:
  imports:
    - sphinx_sitemap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jdillard/sphinx-sitemap
  summary: Sitemap generator for Sphinx
  license: MIT
  license_file: LICENSE
  doc_url: https://sphinx-sitemap.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
