{% set name = "sphinx-sitemap" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 984bef068bbdbc26cfae209a8b61392e9681abc9191b477cd30da406e3a60ee5

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - six
    - sphinx >=1.2

test:
  imports:
    - sphinx_sitemap
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jdillard/sphinx-sitemap
  dev_url: https://github.com/jdillard/sphinx-sitemap
  doc_url: https://sphinx-sitemap.readthedocs.io/
  summary: Sitemap generator for Sphinx
  description: |
    A Sphinx extension to generate multi-version and multi-language sitemaps.org compliant sitemaps 
    for the HTML version of your Sphinx documentation.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
