{% set version = "2.4.0" %}

package:
  name: sphinx-sitemap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx-sitemap/sphinx-sitemap-{{ version }}.tar.gz
  sha256: 3e19cff281974c00dfdc72d2d6ac71b737805dbd5666019997a4ac062a6406c0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - six
    - sphinx >=1.2

test:
  imports:
    - sphinx_sitemap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jdillard/sphinx-sitemap
  summary: Sitemap generator for Sphinx
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
