{% set version = "2.2.1" %}

package:
  name: sphinx-sitemap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx-sitemap/sphinx-sitemap-{{ version }}.tar.gz
  sha256: f1f2149c8013b6d68cc48e6b5bd90f088658cd4584c0220224e72ca85d07b92b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - six
    - sphinx >=1.2

test:
  imports:
    - sphinx_sitemap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jdillard/sphinx-sitemap
  summary: Sitemap generator for Sphinx
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
